### ISSUE TITLE
Refactoring suggestions

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/parse-framework#1]
I have been using TypeScript for work and have decided to adopt it for Unibeautify. The objective is to leverage TypeScript's compiler to catch API usage errors along with making it easier for contributors to develop quality code. Since Unibeautify-core and the parse-framework as for-developers-by-developers it makes sense to use TypeScript and automatically generate typing definitions. It will be up to the developer of each individual beautifier whether or not they want to utilize these generate typings by using TypeScript also, or simply develop in JavaScript.

Also, the `parse.js` really needs to be broken into smaller, more modular files.

**Comment by prettydiff** [comment]
This was just to establish the repo with an initial commit.  I am planning on deleting half that file and possibly as much as two-thirds.

**Comment by Glavin001** [comment]
Sounds good! I figured.

What are your thoughts on using TypeScript, @prettydiff ?

**Comment by bitwiseman** [comment]
@Glavin001 - I'm fine with Typescript.  However, I should probably make it so js-beautify understands it before I start using it. 😄
