### ISSUE TITLE
Performance questions

### ISSUE THREAD

**Issue by prettydiff** [Unibeautify/parse-framework#40]
On my current system this application appears to be the fastest JavaScript parser written in JavaScript.  I am having **serious reservations** accepting that conclusion.  When I published this application last summer it was twice as slow as Esprima, the fastest JavaScript parser written in JavaScript.

I wrote a performance utility to examine speed with some amount of precision:
https://github.com/Unibeautify/parse-framework/blob/master/services.ts#L507-L539

I am using this page as a frame of reference to compare the times in this application against the performance of other JavaScript parsers written in JavaScript: http://esprima.org/test/compare.html  Please be sure you are in Google Chrome when visiting that page so that the numbers are a more accurate reflection to anything generated in Node since Node and Chrome use the same JavaScript engine.

In order to run a proper comparison I download the same version of jQuery Mobile Esprima is testing against: http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.js

To run the performance follow these steps:

```bash
git clone git@github.com:Unibeautify/parse-framework.git
cd parse-framework
tsc
node js/services build
node js/services performance ..\jquery.mobile-1.4.2.min.js
```

What I know has changed from publication time to now:

* When I published this utility I was on a latest model macbook pro.  Currently I am stuck on a windows box with really nice hardware.  Node generally runs slower on Windows, but I have a superior CPU and 64gb ram.
* I just updated performance utility in this application realizing that there was an opportunity to increase transparency in the numbers.
* The version number on Esprima has not changed in more than a year: https://github.com/jquery/esprima/commit/51f48deaa190686265f3f962d6dc5c30dd078dde
* I have not modified the lexer libraries in this application (the files that do the actual parsing) since publication time.
* I updated Chrome and Node to the latest versions as of today to ensure software version misalignment isn't a factor.
   - Chrome - Version 65.0.3325.146 (Official Build) (64-bit)
   - Node - v9.8.0

The only conclusion I can come to so far is that my little parse-framework application generates similar performance numbers on Windows and OSX while other parsers are several times slower in Windows Chrome.

**Comment by szeck87** [comment]
When you run the tests in http://esprima.org/test/compare.html, did you uncheck  Run each parse in a separate Web Worker thread?

**Comment by prettydiff** [comment]
Thanks.  That produces the numbers I remember seeing.

**Comment by szeck87** [comment]
Yea, if you wanted to compare apples to apples, use benchmark 1.0.0 like they are doing.  You could also use webpack to bundle everything together, it might give it a small speed boost.

But considering it parses a whole bunch of languages, 215 ms is pretty incredible.

**Comment by prettydiff** [comment]
Maybe, but I really think they are doing something more intelligent.  In that jQuery code sample 40% of the parsing time is spent just on comments and strings.  My thinking is that I am scanning each character in order, and Esprima is probably taking a smarter approach.

I will look at this more once I get Pretty Diff 3 online.  I am getting close.
