### ISSUE TITLE
Help with nodejs setup

### ISSUE THREAD

**Issue by quangkieu** [Unibeautify/parse-framework#43]
Hi,
I know that I am a newbie in nodejs and its build tool.
So I tried to look looking to add vbscript (most of syntax somewhat like c) and I tried to use https://glitch.com as dev environment. I got error when doing cmd
```
npm install -g typescript
npm install -g eslint
```
permission denied, mkdir '/home/nvm/.nvm/versions/node/v8.11.1/pnpm-global/1_shamefully_flatten'

**Comment by prettydiff** [comment]
I am not familiar with PNPM.  I believe it is https://github.com/pnpm/pnpm which looks like a different form of package manager.  Perhaps it could be related to https://github.com/pnpm/pnpm/issues/1097

Did you attempt to install typescript and eslint as separate commands?  If so did either of them install successfully?
