### ISSUE TITLE
JSON - remove whitespace at start and end of key names

### ISSUE THREAD

**Issue by prettydiff** [Unibeautify/parse-framework#67]
https://github.com/Glavin001/atom-beautify/issues/2306

**Comment by bitwiseman** [comment]
@prettydiff  So, the intent is to cleanup invalid input?  BTW, whitespace is allowed in key names and is valid input. It is unescaped newlines in strings that are not allowed - anywhere.

**Comment by prettydiff** [comment]
Thanks, I didn't know any of that.  I think the original poster's intent seems to be to remove white space at the start or end of key names.  I will probably just convert the newlines to `\n` entities in the parser.
